### ISSUE TITLE
pls help: right password but return 403

### ISSUE THREAD

**Issue by jun14** [lord/pinboard-to-instapaper#1]
./transfer.rb:19:in `post_to_instapaper': Instapaper failed to authorize! (RuntimeError)
	from ./transfer.rb:36:in `block in <main>'
	from ./transfer.rb:35:in `each'
	from ./transfer.rb:35:in `<main>

I verified the password but returns 403.

**Comment by lord** [comment]
Ah, sorry, I wrote this script 4 years ago, and I have no idea what the error could be.

**Comment by jun14** [comment]
thx anyway

**Comment by jun14** [comment]
nailed,  I don't know if it was instapaper's 'username' system going wrong, I retried with my account name (email), authorization passed!

**Comment by lord** [comment]
:+1: glad it works now!
